package SEARCHING;

public class NOTE {
    // binary SEARCH IS FASTER THAN THE LINEAR SEARCH BECAUSE IT BREAKS THE
// THE PROGRAM IN TWO PARTS AND FINDS THE INDEX FASTER AND IN LINEAR SEARCH
// IT FINDS THE INDEX ONE BY ONE ...SO THE TIME COMPLEXITY OF BINARY SEARCH
// IS GOOD RATHER THAN LINEAR SEARCH ....BUT THE PROBLEM WITH BINARY SEARCH
// IS THAT IT SHOULD BE IN THE INCREASING ORDER OR DECREASING ORDER ....
//    IT WONT WORK IF THE ARRAY IF THE ARRAY IS DISORGANIZED


}
